version: "3.9"

services:
  app:
    build: .
    container_name: book_store
    ports:
      - "7005:7005"
    environment:
      PORT: 7005
      MONGODB_URI: mongodb://mongo:27017/crudusersdb
    depends_on:
      - mongo
    networks:
      - crud_app_network

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - crud_app_network

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo
    networks:
      - crud_app_network

volumes:
  mongo_data:

networks:
  crud_app_network:
    driver: bridge
