services:
  app:
    build: .
    container_name: crud_app
    ports:
      - "7005:7005"
    environment:
      PORT: 7005
      MONGODB_URI: mongodb://mongo:27017/crudusersdb   
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - crud_app_network

  mongo:
    image: mongo:6
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - crud_app_network

volumes:
  mongo_data:

networks:
  crud_app_network:
    driver: bridge
